# Source: models/templates/models.yaml
apiVersion: kubeai.org/v1
kind: Model
metadata:
  name: qwen2-500m-instruct-llamacpp-cpu
spec:
  features:
    - TextGeneration
  url: hf://Qwen/Qwen2.5-0.5B-Instruct-GGUF:q4_k_m
  engine: LlamaCpp
  args:
    - --ctx-size
    - "4096"
  minReplicas: 0
  resourceProfile: cpu:1
