# Create a GitHub release on tag push
# source: https://stackoverflow.com/a/75679739/376445
name: Create GitHub Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          if gh release view "$tag" --repo="$GITHUB_REPOSITORY" >/dev/null 2>&1; then
              echo "Release $tag already exists, skipping."
              exit 0
          fi
          gh release create "$tag" \
            --repo="$GITHUB_REPOSITORY" \
            --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
            --generate-notes
